# Generated by Django 4.0.2 on 2022-02-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0003_alter_userprofile_floor_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_key',
            field=models.IntegerField(),
        ),
    ]
