# Generated by Django 4.0.2 on 2022-02-27 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0004_alter_floor_floor_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='floor_key',
        ),
    ]
