# Generated by Django 4.0.2 on 2022-02-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0007_alter_userprofile_floor_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='floor_key',
            new_name='floor',
        ),
    ]
