# Generated by Django 4.0.2 on 2022-02-27 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0008_rename_floor_key_userprofile_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserView.floor'),
        ),
    ]
