# Generated by Django 4.0.2 on 2022-02-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0009_alter_userprofile_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='floor_key',
            field=models.IntegerField(null=True),
        ),
    ]
