# Generated by Django 4.0.2 on 2022-02-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0011_remove_userprofile_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='floor_key',
            new_name='floor_num',
        ),
    ]
