# Generated by Django 4.0.2 on 2022-03-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0002_alter_userprofile_floor_key 2'),
        ('UserView', '0003_alter_userprofile_floor_key 2'),
        ('UserView', '0004_alter_floor_floor_key 2'),
        ('UserView', '0005_remove_userprofile_floor_key 2'),
        ('UserView', '0006_userprofile_floor_key 2'),
        ('UserView', '0007_alter_userprofile_floor_key 2'),
        ('UserView', '0008_rename_floor_key_userprofile_floor 2'),
        ('UserView', '0009_alter_userprofile_floor 2'),
        ('UserView', '0010_userprofile_floor_key 2'),
        ('UserView', '0011_remove_userprofile_floor 2'),
        ('UserView', '0012_rename_floor_key_floor_floor_num'),
        ('UserView', '0012_rename_floor_key_floor_floor_num 2'),
    ]

    operations = [
    ]
